version: 2
updates:
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Chicago"

  - package-ecosystem: "elm"
    directory: "/review"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Chicago"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Chicago"
