name: CI

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: "Lint, Test, Publish"
    runs-on: ubuntu-latest
    permissions:
      checks: write # elm-review-action

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Elm tools and cache $ELM_HOME
        uses: mpizenberg/elm-tooling-action@cbc43aedc689be4271ecec1bdd18755a6ed7f8f3 # v2.1.0
        with:
          cache-key: elm-tooling.json

      - name: elm-format
        uses: sparksp/elm-format-action@c1e0bea196510423a34233b8ac8c5fb17cf010b6 # v1.0.4

      - name: elm-review
        uses: sparksp/elm-review-action@392d83b512d9ab818a5b1588599248944416311f # v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          elm_review: ./review/elm-review.ps1
          elm_compiler: ./node_modules/.bin/elm
          elm_format: ./node_modules/.bin/elm-format

      - name: elm-verify-examples
        run: npx elm-verify-examples@6.0.3

      - name: elm-test-rs
        run: ./node_modules/.bin/elm-test-rs

      - uses: dillonkearns/elm-publish-action@deab1ae44c3ce214c27183060bbccd7c98d3b1f1 # v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-elm: ./node_modules/.bin/elm
